In [1]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [2]:
folder = '/gdrive/MyDrive/data/'

In [3]:
!ls '/gdrive/MyDrive/data/'

bible_fra.txt	   glove.6B.100d.txt			     tweets.csv
births.csv	   glove.6B.200d.txt			     WASTE_COURT.zip
births_github.csv  glove.6B.300d.txt			     WASTE.zip
decades.csv	   glove.6B.50d.txt
exemple.txt	   Synthetic_Financial_datasets_log.csv.zip


In [4]:
folder + "bible_fra.txt"
# Source originale: https://raw.githubusercontent.com/BibleNLP/ebible/refs/heads/main/corpus/fra-fraLSG.txt

'/gdrive/MyDrive/data/bible_fra.txt'

In [5]:
with open(folder + "bible_fra.txt", "r") as f:
  lines = f.readlines()

In [6]:
type(lines), len(lines)

(list, 41899)

In [7]:
lines[45]

'L’Éternel Dieu prit l’homme, et le plaça dans le jardin d’Éden pour le cultiver et pour le garder.\n'

In [8]:
lines[6]

'Et Dieu fit l’étendue, et il sépara les eaux qui sont au-dessous de l’étendue d’avec les eaux qui sont au-dessus de l’étendue. Et cela fut ainsi.\n'

In [9]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

# Nettoyage du corpus

In [10]:
lines[0]

'Au commencement, Dieu créa les cieux et la terre.\n'

In [11]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

In [12]:
corpus = []
for line in lines:
  line = line.split('\n')[0]
  line = line.lower()
  if line:
    corpus.append(line)

In [13]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

In [14]:
lines[25000].split('\n')[0]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.'

In [15]:
bool(lines[25000].split('\n')[0])

True

In [16]:
corpus[25000]

'il a son van à la main; il nettoiera son aire, et il amassera le blé dans son grenier, mais il brûlera la paille dans un feu qui ne s’éteint point.'

In [17]:
lines[0]

'Au commencement, Dieu créa les cieux et la terre.\n'

In [18]:
corpus[0]

'au commencement, dieu créa les cieux et la terre.'

In [19]:
len(corpus)

31060

In [20]:
corpus = corpus[:7000]

In [21]:
len(corpus)

7000

# Tokenisation

In [22]:
corpus[45]

'l’éternel dieu prit l’homme, et le plaça dans le jardin d’éden pour le cultiver et pour le garder.'

In [23]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [24]:
tokenizer = Tokenizer()

In [25]:
tokenizer.fit_on_texts(corpus)

In [26]:
len(tokenizer.word_index)

9421

In [27]:
corpus[3]

'dieu vit que la lumière était bonne; et dieu sépara la lumière d’avec les ténèbres.'

In [28]:
seq = tokenizer.texts_to_sequences([corpus[3]])[0]

In [29]:
seq

[27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282, 5, 1541]

In [30]:
for i in range(1, len(seq)):
  print(f'{i:>2}', seq[:i+1])

 1 [27, 278]
 2 [27, 278, 9]
 3 [27, 278, 9, 4]
 4 [27, 278, 9, 4, 1840]
 5 [27, 278, 9, 4, 1840, 78]
 6 [27, 278, 9, 4, 1840, 78, 1101]
 7 [27, 278, 9, 4, 1840, 78, 1101, 1]
 8 [27, 278, 9, 4, 1840, 78, 1101, 1, 27]
 9 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660]
10 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4]
11 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840]
12 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282]
13 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282, 5]
14 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282, 5, 1541]


In [31]:
sequences = tokenizer.texts_to_sequences(corpus)

In [32]:
input_sequences = []

for seq in sequences:
  for i in range(1, len(seq)):
    data_line = seq[:i+1]
    input_sequences.append(data_line)

In [33]:
len(input_sequences)

163541

In [34]:
input_sequences[7:12]

[[29, 2045, 27, 1540, 5, 547, 1, 4, 90],
 [4, 90],
 [4, 90, 78],
 [4, 90, 78, 5560],
 [4, 90, 78, 5560, 1]]

# Padding

In [35]:
max([len(x) for x in input_sequences])

65

In [36]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [37]:
input_sequences = pad_sequences(input_sequences, padding="pre", maxlen=65)

In [38]:
input_sequences[7:12]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,   29, 2045,   27, 1540,    5,  547,    1,    4,   90],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    4,   90],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0

# Creating x_train et y_train

In [39]:
input_sequences.shape

(163541, 65)

In [40]:
x_train = input_sequences[:, :-1]
y_train = input_sequences[:, -1]

In [41]:
x_train.shape, y_train.shape

((163541, 64), (163541,))

In [42]:
x_train[6]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,   29, 2045,   27, 1540,    5,  547,    1], dtype=int32)

In [43]:
int(y_train[6])

4

In [44]:
import tensorflow as tf

In [45]:
tf.keras.utils.to_categorical([4, 2, 1])

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [46]:
y_train = tf.keras.utils.to_categorical(y_train)

In [47]:
y_train[6]

array([0., 0., 0., ..., 0., 0., 0.])

In [48]:
y_train.shape

(163541, 9422)

# Modeling

In [49]:
import numpy as np

In [50]:
np.power(66, 1/4)

np.float64(2.8502698827717983)

In [51]:

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Embedding(9421, 16),
        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
        tf.keras.layers.Dense(9421, activation='softmax'),
    ]
)

model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])


In [52]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
h = model.fit(x_train, y_train, epochs=20, batch_size=2048)

# Generer du Texte

In [ ]:
x_train.shape

In [ ]:
prompt = "dieu est"

In [ ]:
prompt_seq = tokenizer.texts_to_sequences([prompt])
prompt_seq

In [ ]:
prompt_seq[0]

In [ ]:
prompt_x = pad_sequences([prompt_seq[0]], padding="pre", maxlen=65)

In [ ]:
prompt_x.shape

In [ ]:
prompt_x

In [ ]:
pred = model.predict(prompt_x)

In [ ]:
pred

In [ ]:
import numpy as np

In [ ]:
np.argmax(pred)

In [ ]:
tokenizer.index_word

In [ ]:
tokenizer.index_word.get(18)

In [ ]:
prompt = "La tente d'assignation"

n_predict = 10

for _ in range(n_predict):
  prompt_seq = tokenizer.texts_to_sequences([prompt])
  prompt_x = pad_sequences([prompt_seq[0]], padding="pre", maxlen=65)
  pred = model.predict(prompt_x)
  index = np.argmax(pred)
  mot_predit = tokenizer.index_word.get(index)
  print(prompt + " " + mot_predit)
  prompt = prompt + " " + mot_predit

In [ ]:
corpus[36]

In [ ]:
90