In [130]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [131]:
folder = '/gdrive/MyDrive/data/'

In [132]:
!ls '/gdrive/MyDrive/data/'

bible_fra.txt	   glove.6B.100d.txt			     tweets.csv
births.csv	   glove.6B.200d.txt			     WASTE_COURT.zip
births_github.csv  glove.6B.300d.txt			     WASTE.zip
decades.csv	   glove.6B.50d.txt
exemple.txt	   Synthetic_Financial_datasets_log.csv.zip


In [133]:
folder + "bible_fra.txt"
# Source originale: https://raw.githubusercontent.com/BibleNLP/ebible/refs/heads/main/corpus/fra-fraLSG.txt

'/gdrive/MyDrive/data/bible_fra.txt'

In [134]:
with open(folder + "bible_fra.txt", "r") as f:
  lines = f.readlines()

In [135]:
type(lines), len(lines)

(list, 41899)

In [136]:
lines[45]

'L’Éternel Dieu prit l’homme, et le plaça dans le jardin d’Éden pour le cultiver et pour le garder.\n'

In [137]:
lines[6]

'Et Dieu fit l’étendue, et il sépara les eaux qui sont au-dessous de l’étendue d’avec les eaux qui sont au-dessus de l’étendue. Et cela fut ainsi.\n'

In [138]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

# Nettoyage du corpus

In [139]:
lines[0]

'Au commencement, Dieu créa les cieux et la terre.\n'

In [140]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

In [141]:
corpus = []
for line in lines:
  line = line.split('\n')[0]
  line = line.lower()
  if line:
    corpus.append(line)

In [142]:
lines[25000]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.\n'

In [143]:
lines[25000].split('\n')[0]

'Dans ce même temps, Marie se leva, et s’en alla en hâte vers les montagnes, dans une ville de Juda.'

In [144]:
bool(lines[25000].split('\n')[0])

True

In [145]:
corpus[25000]

'il a son van à la main; il nettoiera son aire, et il amassera le blé dans son grenier, mais il brûlera la paille dans un feu qui ne s’éteint point.'

In [146]:
lines[0]

'Au commencement, Dieu créa les cieux et la terre.\n'

In [147]:
corpus[0]

'au commencement, dieu créa les cieux et la terre.'

In [148]:
len(corpus)

31060

In [149]:
corpus = corpus[:7000]

In [150]:
len(corpus)

7000

# Tokenisation

In [151]:
corpus[45]

'l’éternel dieu prit l’homme, et le plaça dans le jardin d’éden pour le cultiver et pour le garder.'

In [152]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [153]:
tokenizer = Tokenizer()

In [154]:
tokenizer.fit_on_texts(corpus)

In [155]:
len(tokenizer.word_index)

9421

In [156]:
corpus[3]

'dieu vit que la lumière était bonne; et dieu sépara la lumière d’avec les ténèbres.'

In [157]:
seq = tokenizer.texts_to_sequences([corpus[3]])[0]

In [158]:
seq

[27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282, 5, 1541]

In [159]:
for i in range(1, len(seq)):
  print(f'{i:>2}', seq[:i+1])

 1 [27, 278]
 2 [27, 278, 9]
 3 [27, 278, 9, 4]
 4 [27, 278, 9, 4, 1840]
 5 [27, 278, 9, 4, 1840, 78]
 6 [27, 278, 9, 4, 1840, 78, 1101]
 7 [27, 278, 9, 4, 1840, 78, 1101, 1]
 8 [27, 278, 9, 4, 1840, 78, 1101, 1, 27]
 9 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660]
10 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4]
11 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840]
12 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282]
13 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282, 5]
14 [27, 278, 9, 4, 1840, 78, 1101, 1, 27, 2660, 4, 1840, 2282, 5, 1541]


In [160]:
sequences = tokenizer.texts_to_sequences(corpus)

In [161]:
input_sequences = []

for seq in sequences:
  for i in range(1, len(seq)):
    data_line = seq[:i+1]
    input_sequences.append(data_line)

In [162]:
len(input_sequences)

163541

In [163]:
input_sequences[7:12]

[[29, 2045, 27, 1540, 5, 547, 1, 4, 90],
 [4, 90],
 [4, 90, 78],
 [4, 90, 78, 5560],
 [4, 90, 78, 5560, 1]]

# Padding

In [164]:
max([len(x) for x in input_sequences])

65

In [165]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [166]:
input_sequences = pad_sequences(input_sequences, padding="pre", maxlen=65)

In [167]:
input_sequences[7:12]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,   29, 2045,   27, 1540,    5,  547,    1,    4,   90],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    4,   90],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0

# Creating x_train et y_train

In [168]:
input_sequences.shape

(163541, 65)

In [169]:
x_train = input_sequences[:, :-1]
y_train = input_sequences[:, -1]

In [170]:
x_train.shape, y_train.shape

((163541, 64), (163541,))

In [171]:
x_train[6]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,   29, 2045,   27, 1540,    5,  547,    1], dtype=int32)

In [172]:
int(y_train[6])

4

In [173]:
import tensorflow as tf

In [174]:
tf.keras.utils.to_categorical([4, 2, 1])

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [175]:
y_train = tf.keras.utils.to_categorical(y_train)

In [176]:
y_train[6]

array([0., 0., 0., ..., 0., 0., 0.])

In [177]:
y_train.shape

(163541, 9422)

# Modeling

In [178]:
import numpy as np

In [179]:
np.power(65, 1/4)

np.float64(2.8394115144336776)

In [180]:
# model = tf.keras.models.Sequential(
#     [
#         tf.keras.layers.Embedding(9422, 8),
#         tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(8)),
#         tf.keras.layers.Dense(9422, activation='softmax'),
#     ]
# )

# model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

# h = model.fit(x_train, y_train, epochs=20, batch_size=2048)

# model.summary()

In [181]:
# This cell is now empty as its content has been moved to cell bhqocjStWtKQ

In [182]:
import tensorflow as tf

In [183]:
# This cell is now empty as its content has been moved to cell bhqocjStWtKQ

# Generer du Texte

In [184]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

def data_generator(sequences, vocab_size, max_len, batch_size):
  """
  Generates batches of padded input sequences and one-hot encoded target sequences.

  Args:
    sequences: A list of integer sequences.
    vocab_size: The size of the vocabulary.
    max_len: The maximum length of the input sequences after padding.
    batch_size: The number of samples per batch.

  Yields:
    A tuple containing a batch of padded input sequences and a batch of one-hot
    encoded target sequences.
  """
  while True:
    batch_x = []
    batch_y = []
    for seq in sequences:
      for i in range(1, len(seq)):
        input_seq = seq[:i+1]
        padded_input = pad_sequences([input_seq[:-1]], padding="pre", maxlen=max_len - 1)[0]
        output_token = input_seq[-1]
        one_hot_output = to_categorical([output_token], num_classes=vocab_size)[0]

        batch_x.append(padded_input)
        batch_y.append(one_hot_output)

        if len(batch_x) == batch_size:
          yield np.array(batch_x), np.array(batch_y)
          batch_x = []
          batch_y = []

    if batch_x: # Yield any remaining samples in the last batch
        yield np.array(batch_x), np.array(batch_y)

# Define parameters
vocab_size = len(tokenizer.word_index) + 1 # Add 1 for padding
max_len = 65
batch_size = 2048

# Create the data generator
train_generator = data_generator(sequences, vocab_size, max_len, batch_size)

# Modify the model fitting to use the generator
# Calculate steps per epoch
total_samples = sum([len(seq) - 1 for seq in sequences])
steps_per_epoch = total_samples // batch_size

model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Embedding(vocab_size, 16),
        tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
        tf.keras.layers.Dense(vocab_size, activation='softmax'),
    ]
)

model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])

h = model.fit(train_generator, epochs=20, steps_per_epoch=steps_per_epoch)

model.summary()

Epoch 1/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 218s 3s/step - accuracy: 0.0269 - loss: 8.1035
Epoch 2/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 209s 3s/step - accuracy: 0.0483 - loss: 6.6160
Epoch 3/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 209s 3s/step - accuracy: 0.0484 - loss: 6.5405
Epoch 4/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 209s 3s/step - accuracy: 0.0483 - loss: 6.4306
Epoch 5/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 208s 3s/step - accuracy: 0.0523 - loss: 6.3414
Epoch 6/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 211s 3s/step - accuracy: 0.0613 - loss: 6.2597
Epoch 7/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 209s 3s/step - accuracy: 0.0666 - loss: 6.2079
Epoch 8/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 208s 3s/step - accuracy: 0.0716 - loss: 6.1332
Epoch 9/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 208s 3s/step - accuracy: 0.0758 - loss: 6.0593
Epoch 10/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 209s 3s/step - accuracy: 0.0819 - loss: 6.0175
Epoch 11/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 207s 3s/step - accuracy: 0.0854 - loss: 5.9810
Epoch 12/20
79/79 ━━━━━━━━━━━━━━━━━━━━ 207s 3s/step - accuracy:

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 64, 16)         │       150,752 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_2 (Bidirectional) │ (None, 128)            │        41,472 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 9422)           │     1,215,438 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,222,988 (16.11 MB)

 Trainable params: 1,407,662 (5.37 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2,815,326 (10.74 MB)

In [185]:
x_train.shape

(163541, 64)

In [186]:
prompt = "dieu est"

In [187]:
prompt_seq = tokenizer.texts_to_sequences([prompt])
prompt_seq

[[27, 45]]

In [188]:
prompt_seq[0]

[27, 45]

In [189]:
prompt_x = pad_sequences([prompt_seq[0]], padding="pre", maxlen=max_len - 1)

In [190]:
prompt_x.shape

(1, 64)

In [191]:
prompt_x

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 27, 45]],
      dtype=int32)

In [192]:
pred = model.predict(prompt_x)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 542ms/step


In [193]:
pred

array([[5.1976226e-08, 4.9878340e-02, 1.2880805e-02, ..., 3.1221757e-06,
        7.4884633e-07, 1.8478706e-06]], dtype=float32)

In [194]:
import numpy as np

In [195]:
np.argmax(pred)

np.int64(1)

In [196]:
tokenizer.index_word

{1: 'et',
 2: 'de',
 3: 'le',
 4: 'la',
 5: 'les',
 6: 'à',
 7: 'il',
 8: 'l’éternel',
 9: 'que',
 10: 'des',
 11: 'vous',
 12: 'qui',
 13: 'tu',
 14: 'pour',
 15: 'en',
 16: 'du',
 17: 'dans',
 18: 'un',
 19: 'ne',
 20: 'je',
 21: 'ce',
 22: 'sur',
 23: 'fils',
 24: 'dit',
 25: 'ils',
 26: 'son',
 27: 'dieu',
 28: 'lui',
 29: 'au',
 30: 'avec',
 31: 'point',
 32: 'une',
 33: 'pays',
 34: 'ton',
 35: 'se',
 36: 'sa',
 37: 'moïse',
 38: 'nous',
 39: 'a',
 40: 'ses',
 41: 'leur',
 42: 'd’israël',
 43: 'tout',
 44: 'enfants',
 45: 'est',
 46: 'pas',
 47: 'tous',
 48: 'par',
 49: 'leurs',
 50: 'toi',
 51: 'sera',
 52: 'comme',
 53: 'devant',
 54: 'car',
 55: 'peuple',
 56: 'qu’il',
 57: 'c’est',
 58: 'elle',
 59: 'te',
 60: 'si',
 61: 'avait',
 62: 'moi',
 63: 'deux',
 64: 'tes',
 65: 'jour',
 66: 'aux',
 67: 'mon',
 68: 'y',
 69: 'mais',
 70: 'voici',
 71: 'fait',
 72: 'on',
 73: 'père',
 74: 'femme',
 75: 'sont',
 76: 'vos',
 77: 'fit',
 78: 'était',
 79: 'ta',
 80: 'votre',
 81: 'ces',


In [204]:
tokenizer.index_word.get(2)

'de'

In [198]:
prompt = "La tente d'assignation"

n_predict = 10

for _ in range(n_predict):
  prompt_seq = tokenizer.texts_to_sequences([prompt])
  prompt_x = pad_sequences([prompt_seq[0]], padding="pre", maxlen=max_len -1)
  pred = model.predict(prompt_x)
  index = np.argmax(pred)
  mot_predit = tokenizer.index_word.get(index)
  print(prompt + " " + mot_predit)
  prompt = prompt + " " + mot_predit

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
La tente d'assignation d’assignation
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
La tente d'assignation d’assignation et
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
La tente d'assignation d’assignation et les
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
La tente d'assignation d’assignation et les enfants
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
La tente d'assignation d’assignation et les enfants de
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
La tente d'assignation d’assignation et les enfants de la
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
La tente d'assignation d’assignation et les enfants de la enfants
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
La tente d'assignation d’assignation et les enfants de la enfants de
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
La tente d'assignation d’assignation et les enfants de la enfants de la
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
La tente d'assignation d’assignation et les enfants de la enfants de la enfants


In [199]:
corpus[36]

'mais une vapeur s’éleva de la terre, et arrosa toute la surface du sol.'

In [200]:
90

90

# Task
Améliore le code pour réduire la consommation de mémoire afin qu'il puisse s'exécuter avec 12 Go de RAM, en expliquant les modifications en français.

## Inspecter l'utilisation de la mémoire

### Subtask:
Identifier les variables qui consomment le plus de mémoire.


**Reasoning**:
Use the `%whos` magic command to list all variables and their memory usage to identify large variables.



In [201]:
%whos

Variable          Type             Data/Info
--------------------------------------------
Tokenizer         type             <class 'keras.src.legacy.<...>ocessing.text.Tokenizer'>
batch_size        int              2048
corpus            list             n=7000
data_generator    function         <function data_generator at 0x7a732d8da520>
data_line         list             n=23
drive             module           <module 'google.colab.dri<...>s/google/colab/drive.py'>
f                 TextIOWrapper    <_io.TextIOWrapper name='<...>ode='r' encoding='utf-8'>
folder            str              /gdrive/MyDrive/data/
h                 History          <keras.src.callbacks.hist<...>object at 0x7a6f86169f70>
i                 int              22
index             int64            44
input_sequences   ndarray          163541x65: 10630165 elems, type `int32`, 42520660 bytes (40.55086135864258 Mb)
line              str              
lines             list             n=41899
max_len           i

**Reasoning**:
The previous `%whos` command was executed in an empty namespace. Re-executing the cells up to the point where the data and sequences are processed will populate the namespace, allowing for identification of large variables using `%whos`.



In [202]:
from google.colab import drive
drive.mount('/gdrive')
folder = '/gdrive/MyDrive/data/'
with open(folder + "bible_fra.txt", "r") as f:
  lines = f.readlines()
corpus = []
for line in lines:
  line = line.split('\n')[0]
  line = line.lower()
  if line:
    corpus.append(line)
corpus = corpus[:7000]
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(corpus)
sequences = tokenizer.texts_to_sequences(corpus)
input_sequences = []

for seq in sequences:
  for i in range(1, len(seq)):
    data_line = seq[:i+1]
    input_sequences.append(data_line)
from tensorflow.keras.preprocessing.sequence import pad_sequences
input_sequences = pad_sequences(input_sequences, padding="pre", maxlen=65)
x_train = input_sequences[:, :-1]
y_train = input_sequences[:, -1]
import tensorflow as tf
y_train = tf.keras.utils.to_categorical(y_train)
import numpy as np
%whos

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
Variable          Type             Data/Info
--------------------------------------------
Tokenizer         type             <class 'keras.src.legacy.<...>ocessing.text.Tokenizer'>
batch_size        int              2048
corpus            list             n=7000
data_generator    function         <function data_generator at 0x7a732d8da520>
data_line         list             n=23
drive             module           <module 'google.colab.dri<...>s/google/colab/drive.py'>
f                 TextIOWrapper    <_io.TextIOWrapper name='<...>ode='r' encoding='utf-8'>
folder            str              /gdrive/MyDrive/data/
h                 History          <keras.src.callbacks.hist<...>object at 0x7a6f86169f70>
i                 int              22
index             int64            44
input_sequences   ndarray          163541x65: 10630165 elems, type `int32`, 42520660 bytes (40.55

## Modifier la création des séquences d'entrée et des étiquettes

### Subtask:
Implémenter un générateur ou une approche par lots pour créer les séquences d'entrée (`x_train`) et les étiquettes (`y_train`) à la volée pendant l'entraînement, plutôt que de les stocker entièrement en mémoire.


**Reasoning**:
Implement a data generator to yield batches of padded input sequences and one-hot encoded target sequences to reduce memory consumption during training.

