```
→ model → distance →

→     erreur       →
```

Exemple:

f(x) = 2x → W = 2

g(x) = (f(x) - 2)² # = erreur()

erreur(3) = (f(3) - 2)² = (6 - 2)² = 4² = 16

(3 est W)

```
erreur'   (gof)'
------ =  ------ =  f'(W) * g'(f(W)) = ?
  W'        W'
```
Si ? négatif → forward, sinon backward

W = W - erreur' / W' * 0.0001 (0.0001 est le pas)


In [1]:
import numpy as np

X = np.array([
    [2, 3, -2],
    [4, 5, -1],
    [-5, 2, 3],
    [0, 5, 4]
])


In [2]:
X.shape


(4, 3)

In [3]:
W = np.array([
    [0.02],
    [18],
    [15]
])


In [4]:
W.shape


(3, 1)

In [5]:
# np.dot(X, W) # Produit matriciel Y = W * X
X @ W  # Produit matriciel avec l'opérateur @


array([[ 24.04],
       [ 75.08],
       [ 80.9 ],
       [150.  ]])

In [6]:
# W @ X # Ne marche pas ! Nombre de colonnes de X != Nombre de lignes de 


In [7]:
X, '-'*77, X.T



(array([[ 2,  3, -2],
        [ 4,  5, -1],
        [-5,  2,  3],
        [ 0,  5,  4]]),
 '-----------------------------------------------------------------------------',
 array([[ 2,  4, -5,  0],
        [ 3,  5,  2,  5],
        [-2, -1,  3,  4]]))

In [8]:
X = np.array([[ 2,  4, -5,  0]])
X.T.shape


(4, 1)

In [9]:
W = np.array([
  [0.02],
  [18.0],
  [15.0],
  [-5]
])
W


array([[ 0.02],
       [18.  ],
       [15.  ],
       [-5.  ]])

In [10]:
W = W - X.T * 0.01
W


array([[ 0.  ],
       [17.96],
       [15.05],
       [-5.  ]])