<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/12%20-%20Numpy%20Maths%20et%20Statistiques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 12/30 Numpy : Mathématiques

In [ ]:
import numpy as np


## 1. Méthodes de bases (les plus utiles) de la classe ndarray

In [ ]:
# A = np.array([[1, 2, 3], [4, 5, 6]])
# np.random.seed(0)
# A = np.random.randint(0,10,[2, 3])
A = np.array([[5, 0, 3], [3, 7, 9]])
print(A)
print(f'{A.flatten() = }')

print(A.sum()) # effectue la somme de tous les éléments du tableau
print(A.sum(axis=0)) # effectue la somme des colonnes (somme sur éléments des les lignes)
print(A.sum(axis=1)) # effectue la somme des lignes (somme sur les éléments des colonnes)
print(A.cumsum()) # effectue la somme cumulée

print ("-"*77)
print(A.cumsum(axis=0)) # effectue la somme cumulée / cols
print(A.cumsum(axis=1)) # effectue la somme cumulée / lines
 
print ("-"*77)
print(A.prod()) # effectue le produit
print(A.cumprod()) # effectue le produit cumulé
 
print ("-"*77)
print(A.min()) # trouve le minimum du tableau
print(f"{A.min(axis=1) = }") # trouve le minimum des lines
print(A.min(axis=0)) # trouve le minimum des cols
print(A.max()) # trouve le maximum du tableau
 
print ("-"*77)
print(A.mean()) # calcule la moyenne
print(A.std()) # calcule l'ecart type,
print(A.var()) # calcule la variance
print(A)


[[5 0 3]
 [3 7 9]]
A.flatten() = array([5, 0, 3, 3, 7, 9])
27
[ 8  7 12]
[ 8 19]
[ 5  5  8 11 18 27]
-----------------------------------------------------------------------------
[[ 5  0  3]
 [ 8  7 12]]
[[ 5  5  8]
 [ 3 10 19]]
-----------------------------------------------------------------------------
0
[5 0 0 0 0 0]
-----------------------------------------------------------------------------
0
A.min(axis=1) = array([0, 3])
[3 0 3]
9
-----------------------------------------------------------------------------
4.5
2.9297326385411577
8.583333333333334
[[5 0 3]
 [3 7 9]]


In [ ]:
# A = np.array([[1, 2, 3], [4, 5, 6]])
# np.random.seed(0)
# A = np.random.randint(0,10,[2, 3])
A = np.array([[5, 0, 3], [3, 7, 9]])
print(A)
print(f'{A.flatten() = }')

print(A.sum()) # effectue la somme de tous les éléments du tableau
print(A.sum(axis=0)) # effectue la somme des colonnes (somme sur éléments des les lignes)
print(A.sum(axis=1)) # effectue la somme des lignes (somme sur les éléments des colonnes)
print(A.cumsum()) # effectue la somme cumulée

print ("-"*77)
print(A.cumsum(axis=0)) # effectue la somme cumulée / cols
print(A.cumsum(axis=1)) # effectue la somme cumulée / lines

print ("-"*77)
print(A.prod()) # effectue le produit
print(A.cumprod()) # effectue le produit cumulé

print ("-"*77)
print(A.min()) # trouve le minimum du tableau
print(f"{A.min(axis=0) = }") # trouve le minimum des lines
print(f"{A.min(axis=1) = }") # trouve le minimum des lines
print(f"{A.argmin(axis=0) = }") # trouve la position du minimum des lines
print(f"{A.argmin(axis=1) = }")  # trouve la position du minimum des cols
print(A.max()) # trouve le maximum du tableau

print ("-"*77)
print(A)


[[5 0 3]
 [3 7 9]]
A.flatten() = array([5, 0, 3, 3, 7, 9])
27
[ 8  7 12]
[ 8 19]
[ 5  5  8 11 18 27]
-----------------------------------------------------------------------------
[[ 5  0  3]
 [ 8  7 12]]
[[ 5  5  8]
 [ 3 10 19]]
-----------------------------------------------------------------------------
0
[5 0 0 0 0 0]
-----------------------------------------------------------------------------
0
A.min(axis=0) = array([3, 0, 3])
A.min(axis=1) = array([0, 3])
A.argmin(axis=0) = array([1, 0, 0])
A.argmin(axis=1) = array([1, 0])
9
-----------------------------------------------------------------------------
[[5 0 3]
 [3 7 9]]


In [ ]:
print("-" * 77)
print(f"{float(A.mean()) = }")  # calcule la moyenne
print(f"{float(A.std()) = }")  # calcule l'ecart type,
print("-" * 77)
print(f"{float(A.var()) = }")  # calcule la variance

print("-" * 77)
print(A.mean(axis=0))  # calcule la moyenne des cols
print(A[:, 1].mean())  # calcule la moyenne de col #1

print("-" * 77)
print(A)


-----------------------------------------------------------------------------
float(A.mean()) = 4.5
float(A.std()) = 2.9297326385411577
-----------------------------------------------------------------------------
float(A.var()) = 8.583333333333334
-----------------------------------------------------------------------------
[4.  3.5 6. ]
3.5
-----------------------------------------------------------------------------
[[5 0 3]
 [3 7 9]]


Une méthode tres importante : la méthode **argsort()**

In [ ]:
A = np.random.randint(0, 10, [5, 5]) # tableau aléatoire
print(A)


[[2 7 2 0 0]
 [4 5 5 6 8]
 [4 1 4 9 8]
 [1 1 7 9 9]
 [3 6 7 2 0]]


In [ ]:
print(A.argsort()) # retourne les index pour trier chaque ligne du tableau 
# = print(A.argsort(axis=1))


[[3 4 2 0 1]
 [0 1 2 3 4]
 [1 0 2 4 3]
 [0 1 2 3 4]
 [4 3 0 1 2]]


In [ ]:
print(A.argsort(axis = 0))  # retourne les index pour trier chaque col du tableau


[[3 3 0 0 0]
 [0 2 2 4 4]
 [4 1 1 1 2]
 [1 4 3 2 1]
 [2 0 4 3 3]]


In [ ]:
print(A[:,0].argsort()) # retourne les index pour trier la colonne 0 de A


[3 0 4 1 2]


In [ ]:
A = A[A[:,0].argsort(), :] # trie les colonnes du tableau selon la colonne 0.
A


array([[1, 1, 7, 9, 9],
       [2, 7, 2, 0, 0],
       [3, 6, 7, 2, 0],
       [4, 5, 5, 6, 8],
       [4, 1, 4, 9, 8]], dtype=int32)

In [ ]:
np.exp(A) # exp de chaque val


array([[2.71828183e+00, 2.71828183e+00, 1.09663316e+03, 8.10308393e+03,
        8.10308393e+03],
       [7.38905610e+00, 1.09663316e+03, 7.38905610e+00, 1.00000000e+00,
        1.00000000e+00],
       [2.00855369e+01, 4.03428793e+02, 1.09663316e+03, 7.38905610e+00,
        1.00000000e+00],
       [5.45981500e+01, 1.48413159e+02, 1.48413159e+02, 4.03428793e+02,
        2.98095799e+03],
       [5.45981500e+01, 2.71828183e+00, 5.45981500e+01, 8.10308393e+03,
        2.98095799e+03]])

In [ ]:
np.log(A)  # log de chaque val


C:\Users\utilisateur\AppData\Local\temp\ipykernel_9048\3963381317.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(A)  # log de chaque val


array([[0.        , 0.        , 1.94591015, 2.19722458, 2.19722458],
       [0.69314718, 1.94591015, 0.69314718,       -inf,       -inf],
       [1.09861229, 1.79175947, 1.94591015, 0.69314718,       -inf],
       [1.38629436, 1.60943791, 1.60943791, 1.79175947, 2.07944154],
       [1.38629436, 0.        , 1.38629436, 2.19722458, 2.07944154]])

## 2. Numpy Statistics
Correlation de Pearson :

In [ ]:
B = np.random.randn(3, 3) # nombres aléatoires 3x3
print(B)
print('-'*77)
# retourne la matrice de corrélation de B
print(np.corrcoef(B))


[[-1.04855297 -1.42001794 -1.70627019]
 [ 1.9507754  -0.50965218 -0.4380743 ]
 [-1.25279536  0.77749036 -1.61389785]]
-----------------------------------------------------------------------------
[[ 1.          0.88952232  0.06580918]
 [ 0.88952232  1.         -0.39736254]
 [ 0.06580918 -0.39736254  1.        ]]


In [ ]:
v = np.corrcoef(B)[1, 0]
print(int(v * 10000) / 100, '%')


88.95 %


In [ ]:
# retourne la matrice de corrélation entre les lignes 0 et 1 de B
print(np.corrcoef(B[:,0], B[:, 1]))


[[ 1.         -0.15501074]
 [-0.15501074  1.        ]]


np.unique() :

In [ ]:
np.random.seed(0)
A = np.random.randint(0, 10, [5,5])
A


array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]], dtype=int32)

In [ ]:
np.unique(A)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
v, c = np.unique(A, return_counts=True) # values, counts
v, c


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([1, 2, 1, 3, 2, 3, 2, 4, 4, 3]))

In [ ]:
v[c.argsort()]


array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8], dtype=int32)

In [ ]:
values, counts = np.unique(A, return_counts=True)

for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j} fois')


valeur 0 apparait 1 fois
valeur 2 apparait 1 fois
valeur 1 apparait 2 fois
valeur 4 apparait 2 fois
valeur 6 apparait 2 fois
valeur 3 apparait 3 fois
valeur 5 apparait 3 fois
valeur 9 apparait 3 fois
valeur 7 apparait 4 fois
valeur 8 apparait 4 fois


Calculs statistiques en présence de données manquates (NaN)

In [ ]:
A = np.random.randn(5, 5)
A[0, 2] = np.nan # insere un NaN dans la matrice A
A[4, 3] = np.nan # insere un NaN dans la matrice A
 
print('ratio NaN/size:', (np.isnan(A).sum()/A.size)) # calcule la proportion de NaN dans A
 
print('moyenne sans NaN:', np.nanmean(A)) # calcule la moyenne de A en ignorant les NaN


ratio NaN/size: 0.08
moyenne sans NaN: 0.010707879575141632


In [ ]:
np.isnan(A)


array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]])

In [ ]:
np.isnan(A).sum()


np.int64(2)

## On remplace ces 2 NaN par la nanmean(A)

In [ ]:
A[np.isnan(A)] = np.nanmean(A)
A


array([[ 0.44386323,  0.33367433,  0.01070788, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647],
       [-0.34791215,  0.15634897,  1.23029068,  0.01070788, -0.38732682]])

## 3. Algèbre Linéaire

In [ ]:
A = np.ones((2,3))
B = np.ones((3,2))

print(A)
print('-'*77)
print(A.T) # transposé de la matrice A (c'est un attribut de ndarray)


[[1. 1. 1.]
 [1. 1. 1.]]
-----------------------------------------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
print(A.dot(B)) # produit matriciel A.B
print(B.dot(A)) # produit matriciel A.B


[[3. 3.]
 [3. 3.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [ ]:
A = np.random.randint(0, 10, [3, 3])
 
print('det=', np.linalg.det(A)) # calcule le determinant de A
print('inv A:\n', np.linalg.inv(A)) # calcul l'inverse de A


det= 23.999999999999993
inv A:
 [[-0.5         0.875      -0.25      ]
 [ 0.5        -1.125       0.75      ]
 [-0.          0.33333333 -0.33333333]]


In [ ]:
val, vec = np.linalg.eig(A)
print('valeur propre:\n', val) # valeur propre = eigen value
print('vecteur propre:\n', vec) # vecteur propre = eigen vector


valeur propre:
 [13.58872344 -3.         -0.58872344]
vecteur propre:
 [[-6.70561268e-01 -8.32050294e-01  6.04408531e-01]
 [-5.73889829e-01  1.85511715e-16 -7.73940635e-01]
 [-4.70104297e-01  5.54700196e-01  1.88960901e-01]]


## 4. Exercice et Solution

Standardisez la matrice suivante, c'est a dire effectuez le calcul suivant :
$A = \frac{A - mean(A_{colonne})}{std(A_{colonne})}$

In [ ]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A


array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]], dtype=int32)

In [ ]:
# SOLUTION
D = (A - A.mean(axis=0)) / A.std(axis=0)
D


array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [ ]:
print(D.mean(axis=0)) # les moyennes sont toutes = 0
print(D.std(axis=0)) # les std sont tous = 1 


[-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]
[1. 1. 1. 1. 1.]
